### PR TITLE
Added support for batch processing

### PR DESCRIPTION
**Pull request by snakefoot**
LogglyClient is now reused instead of re-created constantly

Added more logging of exceptions and errors.

### CODE REVIEW

**Comment by neutmute** [comment]
thanks! (full disclosure- i haven't tested it)

**Comment by neutmute** [comment]
I merged this to develop - not master.
Master merge will automatically build a new package for nuget.
Thought I'd wait to see if you will submit PR for netstandard? can merge if you want it now

**Comment by snakefoot** [comment]
> Thought I'd wait to see if you will submit PR for netstandard? 

Will not happen, since I don't want to fiddle with the build-scripts :)

**Comment by snakefoot** [comment]
> can merge if you want it now

Discovered that I was missing the ability to disable the feature. See #13

**Pull request merged**
