### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by neutmute**

### CODE REVIEW

**Comment by snakefoot** [comment]
@neutmute Any change to get a nuget-package published?

**Comment by neutmute** [comment]
doh sorry - thought it would have kicked off automatically

**Comment by neutmute** [comment]
@snakefoot I tried to publish via the existing myget.org config but its giving me headache and need to jump back to other things. You can grab it here for now:

https://www.myget.org/Package/Details/nlog-targets-loggly?packageType=nuget&packageId=NLog.Targets.Loggly&packageVersion=4.7.0.3#

Or if you want to PR a *.yml file that let's it build in AppVeyor - would be happy to cut it over. Myget is a bit frustrating.

**Comment by snakefoot** [comment]
@neutmute Created #22 that changes build.ps1 from using msbuild to dotnet. Removes the need for vswhere etc.

**Pull request merged**
