### PR TITLE
Updated build.ps1 to use dotnet instead of msbuild

### PR DESCRIPTION
**Pull request by snakefoot**

### CODE REVIEW

**Comment by snakefoot** [comment]
@neutmute Maybe consider changing appeveyor-config to pickup nuget-artifacts from `_output`-folder

**Comment by snakefoot** [comment]
Sounds good. Would be nice to get the latest changes out in the wild :)

**Comment by neutmute** [comment]
Worked great - thanks!
https://www.nuget.org/packages/NLog.Targets.Loggly/4.8.5

**Comment by snakefoot** [comment]
Excellent. Thank you for the nuget package


Sent from my Sony Xperia


---- neutmute wrote ----


Worked great - thanks!
https://www.nuget.org/packages/NLog.Targets.Loggly/4.8.5

**Comment by neutmute** [comment]
No problem, now that appveyor works, it only needs a merge to master and it
will auto publish to nuget.

**Pull request merged**
