### PR TITLE
Upgrade to VS2017 and NetStandard2.0

### LINKED ISSUE #11: Upgrade to VS2017 with NetStandard/NetCore
Suggestion for how setup **NLog.Targets.Loggly.csproj**

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net45;netstandard1.5</TargetFrameworks>

    <Title>NLog.Targets.Loggly</Title>
    <Description>A custom target for NLog that sends log messages to loggly.com using the loggly-csharp library</Description>
    <Authors>neutmute</Authors>
    
    <PackageTags>NLog;Loggly</PackageTags>
    <PackageIconUrl>https://raw.githubusercontent.com/neutmute/nlog-targets-loggly/master/SolutionItems/NLoggly.png</PackageIconUrl>
    <PackageProjectUrl>https://github.com/neutmute/nlog-targets-loggly</PackageProjectUrl>

  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' != 'netstandard1.5' ">
    <PackageReference Include="loggly-csharp" Version="4.5.1.6" />
    <PackageReference Include="NLog" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard1.5' ">
    <PackageReference Include="loggly-csharp" Version="4.6.1.45" />
    <PackageReference Include="NLog" Version="4.5.0-rc02" />
  </ItemGroup>

</Project>
```

Commands to have in the build.ps1 (When using VS2017):
```
dotnet restore src\NLog.Targets.Loggly
if (-Not $LastExitCode -eq 0)
{ exit $LastExitCode }

dotnet pack src\NLog.Targets.Loggly --configuration release --include-symbols -o ..\..\artifacts
if (-Not $LastExitCode -eq 0)
{ exit $LastExitCode }
```

### PR DESCRIPTION
**Pull request by snakefoot**
Attempt to resolve #11 (No idea how to test if build script works)

### CODE REVIEW

**Comment by snakefoot** [comment]
@neutmute Have tried to make a shot in the dark with the build-script

**Comment by neutmute** [comment]
Thanks for this. I tried it on my machine and it failed because I don't have msbuild community installed. 

If you can make it work with myget or appveyor - that is sufficient as that is what builds . Best way to test is to make an account with those services and try and run a build.

The build script is easy to execute from your machine: `powershell -f ./build.ps1`
Try and get it working locally and then test on myget. I currently publish via myget but am open to switching to appveyor.

**Comment by snakefoot** [comment]
Think I will leave this job for you.

 I just made a duplicate of the build script's from your other projects (that uses community edition). Surprised you cannot run your own build scripts

Just close this PR if it cannot be used.



Sent from my Samsung device


-------- Original message --------

**Comment by snakefoot** [comment]
@neutmute Tried the following command and the script performs a build:

`PowerShell.exe -ExecutionPolicy Bypass -File .\build.ps1`

**Comment by neutmute** [comment]
ha - maybe it works on one of my machines but not the other. will try the other

**Comment by snakefoot** [comment]
@neutmute Have you found the other machine?

**Comment by neutmute** [comment]
sorry - no. I have no time for this at the moment. If you are able to test locally and vouch the build works then I can merge

**Comment by snakefoot** [comment]
>  @neutmute If you are able to test locally

That is confirmed.

> and maybe on myget too

That I haven't

> I have no time for this at the moment

Think I will just wait for you being able to test and create the actual nuget-package.

**Comment by snakefoot** [comment]
@neutmute Updated to NLog 4.5.0 RTM

**Comment by neutmute** [comment]
thanks for this by the way @snakefoot

**Comment by snakefoot** [comment]
Happy to help out. Hope it brings us closer to the goal of creating a nuget-package.

**Comment by snakefoot** [comment]
@neutmute Any chance that a nuget-package will be published ? (not just to myget).

Could also be nice if the links to MyGet and Nuget-builds pointed to something on ReadMe.md:

https://github.com/neutmute/nlog-targets-loggly/blob/master/README.md

**Comment by neutmute** [comment]
done
https://www.nuget.org/packages/NLog.Targets.Loggly/4.7.0

**Pull request merged**
